OnlineChecklist/Controllers/ChecklistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineChecklist.Controllers
{
    public class ChecklistController : Controller
    {
        // GET: Checklist
        public ActionResult Index(string error)
        {
            Models.ChecklistOverviewModel dashboard = new Models.ChecklistOverviewModel();
            dashboard.MyList = Models.Checklist.GetChecklistsForUser(1);
            dashboard.SuboordinateList = Models.Checklist.GetChecklistsAssignedByMe(1);

            if (error != null)
            {
                dashboard.Error = error;
            }
            else
            {
                dashboard.Error = String.Empty;
            }
            return View(dashboard);
        }

        public ActionResult Status(int? checklistId)
        {
            if (checklistId == null)
            {
                return RedirectToAction("Index", new { error = "You've been redirected back here due to an error. There was no ID given to search. If this happens again, you may want to check your bookmarks." });

            }

            if(!checklistId.GetType().Equals(typeof(int)) || checklistId <= 0)
            {
                return RedirectToAction("Index", new { error = "You've been redirected back here due to an error. The ID given was not an integer or was <= 0. If this happens again, you may want to check your bookmarks." });
            }

            var status = Models.Checklist.GetChecklistStatus((int)checklistId);


            return View(status);
        }
    }
}

OnlineChecklist/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineChecklist.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Goto()
        {
            return View();
        }

        public ActionResult Plan()
        {
            return View();
        }
    }
}

OnlineChecklist/Views/Home/Goto.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<ul>
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Goto", "Goto", "Home")</li>
    <li>@Html.ActionLink("Plan", "Plan", "Home")</li>
    <li>@Html.ActionLink("Checklist/Index", "Index", "Checklist") -- Shows a list of assigned checklists for current logged in user. Also has ability to create and possibly assign checklists. Eventually this will be the real /index</li>
</ul>

OnlineChecklist/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
</div>

OnlineChecklist/Views/Home/Plan.cshtml
@{
    ViewBag.Title = "Plan";
}

<h2>Plan</h2>

<ul>
    <li>Create newly assigned Checklist and redirect to that item</li>
    <li>Assign various info for that Checklist</li>
    <li>Assign so loading user views Assigned Checklists and what checklists they can create on their own</li>
    <li>Maintain New Checklists</li>
    <ul>
        <li>Make a new checklist</li>
        <li>Note worthy items:</li>
        <ul>
            <li>ReqSupvAssignment</li>
        </ul>
        <li>Make new items</li>
        <li>Property types: Group, Subgroup, Action, HasUserLookup, HasSupervisorLookup, HasCustomText, HasURL, ExpectedCompletionDate</li>
    </ul>
    <li>Alerts</li>
    <ul>
        <li>Alert when ExpectedCompletion passed.</li>
        <li>Alert when action is completed.</li>
        <li>Alert when checklist is completed.</li>
    </ul>
    <li>Security Roles</li>
    <ul>
        <li>Administrator</li>
        <li>Supervisor -- Has access to all checklists and can assign checklists</li>
        <li>User</li>
    </ul>
</ul>